version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@form8ion/remark-lint-preset"
    versions:
    - 1.0.12
  - dependency-name: commitlint-config-travi
    versions:
    - 1.3.12
    - 1.3.13
  - dependency-name: lockfile-lint
    versions:
    - 4.6.0
    - 4.6.1
  - dependency-name: remark-toc
    versions:
    - 7.1.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
